### ISSUE TITLE
Display Managers wreck this .Xresources file

### ISSUE THREAD

**Issue by etherealite** [solarized/xresources#1]
If you add this to your ~/.Xresources or ~/.Xdefaults when using the Gnome Display Manager (possibly many others), it will run xrdb with the -nocpp flag, which will cause your define statements such as ```#define S_base03        #002b36``` to be ignored. Terminals and apps will substitute there own values, and you end with a mess, and in some cases unuseable terminals. URXVT is solid pink with text of the exact same color so you can't even use it. Please factor out the #define statements or offer a warning about this unwanted behavior in the readme.

**Comment by blueyed** [comment]
@TrevorBramble 
Is that the script you've mentioned in https://github.com/solarized/xresources/pull/4#issuecomment-30779398?
