### ISSUE TITLE
color variable names confusing

### ISSUE THREAD

**Issue by alecbenzer** [solarized/xresources#5]
The naming of the variables seems a little bit confusing. For instance: in dark mode, we have `#define S_base03        #002b36`, and in light mode, we have `#define S_base03        #fdf6e3`.

But if we look at the solarized values table on the [main site](http://ethanschoonover.com/solarized), we see `base03    #002b36`.

So the entry for the light mode is sort of incorrect.

I think this is done just so that in the common code we can have `*background:              S_base03` work for either light or dark, but it seems like it would be better to have the light and dark sections each name their own `background` variable, instead of changing the value of base03, which should be constant across both schemes (just used in different ways).

**Comment by blueyed** [comment]
:+1: 

See also https://github.com/altercation/solarized/pull/68
